version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      - dependency-name: govspeak
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      # Framework gems
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: rspec-rails
        dependency-type: direct
      - dependency-name: sassc-rails
        dependency-type: direct
